### ISSUE TITLE
age key is jumping off page when looked at on small computer screen

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#175]

**Comment by tomalrussell** [comment]
Max height of legend needs limiting on small-height screens (possibly using `vh` units instead of `rem`? or add a media-query?).

Here's a screenshot of the problem:
![image](https://user-images.githubusercontent.com/2762769/53800316-5ba68600-3f34-11e9-93a4-49d16307e437.png)

Fix should be CSS-only - https://github.com/tomalrussell/colouring-london/blob/master/app/src/frontend/legend.css#L36

**Comment by martin-dj** [comment]
Fix submitted to feature branch which seems to have resolved the issue on small screens.

**Comment by tomalrussell** [comment]
Closed by #225
