### ISSUE TITLE
Suggestion for adding data

### ISSUE THREAD

**Issue by mknkm** [tomalrussell/colouring-london#291]
Polly and I were discussing whether it could be feasible to have a little pop-up window at the cursor when a building polygon is clicked. It feels like a more intuitive way to add the building data in, rather than having to return to the side panel. All the best! Matt

**Comment by tomalrussell** [comment]
Thanks Matt :slightly_smiling_face: it would be neat to keep closer to the building and have the interactions all clustered around one point. This suggestion would avoid the need to glance from map to sidebar and shift focus so often.

We'll stick with the sidebar for now - not least because it's a pretty simple way to design/develop a space for data entry - but will keep ideas of more focussed interaction in mind when next experimenting with the maps UI.
