### ISSUE TITLE
UI: Disclaimer onto screen / modal 

### ISSUE THREAD

**Issue by dominijk** [tomalrussell/colouring-london#306]
Note to affect that data is crowd sourced and caveat against using this, users should use official data sources for items like Listing

**Comment by dominijk** [comment]
Duplicates #277

**Comment by polly64** [comment]
I asked for a wording from UCL for a disclaimer and this has been sent  - it can  also be used as a supplement to the text I have already drafted. So I think we should keep the drafted text on the screen so can be accessed at any time and as it is less aggressive - (this can also come up large on first visit) but also link this to the full UCL disclaimer as below.  Both should also be included separately on the sign up page and also on the download page . It is very important that people understand it is their responsibility for checking the accuracy of the data for their applications not only from our legal point of view but also as a basic issue of getting people have to check 'facts'.

The UCL disclaimer sent to us reads as follows: the data are provided "as is", without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, accuracy, fitness for a particular purpose and non-infringement. In no event shall UCL be liable for any reliance that you place on or how you use the data nor any claim, damages or other liability, whether in an action of contract, tort or otherwise, arising from, out of or in connection with the data or the use or other dealings in the data'.

I also notice on the GLA's London Development database they have this . 

Disclaimer
Whilst every effort has been made to ensure the accuracy of the data, the GLA does not accept any responsibility for any errors or omissions it may contain. The data on this site remains the property of the London Local Authorities, who are required to keep it up to date and accurate.The use of the London Development Database public website is subject to the same Terms & Conditions and Privacy Policy as LONDON.GOV.UK.   

We obviously aren't required to keep the CL data accurate
