### ISSUE TITLE
UI/UX: Top ribbon menu links and names

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#394]
Hi Tom, I have removed the 'more about' wix page and merged its contents with the 'hello' page. This  is now renamed  'About'.  This leaves a bit more room for the page titles. 
From left to right these are:
About ( responsibility polly wix)
Menu (Tom - this is the new Menu navigation page)
Data Categories (polly wix)
View/Edit data (Tom/Dom)
Download (Tom)
Showcase (Polly wix)
Data Ethics (Polly wix)
Analytics (Dom - here we could have your analytics page Dom post Oct, and also the leaderboards)
Sign up/login (Tom)

 Do you think we need a separate technical page or shall we just have the GitHub link on the 'About page?'- this would give us a bit more space on the ribbon

**Comment by dominijk** [comment]
@mz8i @tomalrussell I think this links to issue on the slack thread ?  https://colouringlondon.slack.com/archives/CM3PJTHQV/p1567597752014400

**Comment by dominijk** [comment]
@polly64 For launch I think the Github link is sufficient to cover the technical page

**Comment by mz8i** [comment]
I think we need to have a bit of discussion about the ordering of the links in the menu.
- Because the WIX pages are essentially an external website, when the user is viewing the map and clicks on "About" they are taken outside of the map site, and this disrupts the user flows in a major way. Because of this, my suggestion would be to at least put the View/Edit button first, and only after that any potential about-y links to WIX. While this is not realistic for launch, I would suggest having all the pages as part of the same website, rather than split into Map and WIX. Any thoughts @polly64 @dominijk @tomalrussell?
- I am not entirely clear what is the "Menu" link
- Also, I have noticed that we have an About page as part of the map site, but it is not being linked to currently from anywhere. Is this intentional?

**Comment by dominijk** [comment]
@mz8i post launch the plan is to migrate the WIX content to a platform we control see #296.

**Comment by mz8i** [comment]
Cool, that's what I was hoping for, thanks for clarification. What are your thoughts about the ordering right now?

**Comment by polly64** [comment]
Hi- You should now be able to link to the 'About' page on wix now renamed (previously 'hello') this is the main info page.  The menu page relates to Category menu template #377
Tom/Dom we're having the Mnu page now aren't we? Dom can u email re this and date to meet up, i also need to book Louis.

**Comment by tomalrussell** [comment]
Closing - I think we're satisfied with the menu order for now, further changes can be tracked as part of other issues, e.g.:
- adding leaderboards
- adding links to more pages, including terms/policies (which might mean a menu redesign)
