### ISSUE TITLE
Review Location colour scale

### ISSUE THREAD

**Issue by mz8i** [tomalrussell/colouring-london#575]
As per @polly64 comments, review the colour for ">20%" in the Location colour scale to something that isn't as bright. The suggested colour to test is `#95beba` which is the new suggested colour for conservation areas in Planning. After choosing a base colour, defer to Tarn for designing the full colour scale.

**Comment by polly64** [comment]
@mz8i sorry maciek i've confused things by not being clear . I think we should leave location colour as it is. Then   just copy  the <20% colour from it across to the Planning category' and try it as the 'Conservation Area' colour because it is a bit brighter then what we have now.  So we can close the above issue.
