### ISSUE TITLE
Show edit history

### ISSUE THREAD

**Issue by tomalrussell** [tomalrussell/colouring-london#84]
Add edit history (log) view to building

**Comment by dominijk** [comment]
@tomalrussell is this the back end task? We also have #269 #285 but those are front end

**Comment by tomalrussell** [comment]
This is also front end - to view full history (not just last-edited-by/-date).

Backend interaction might need a small update:
- https://beta.colouringlondon.org/building/2494121.json already returns edit history
- [`queryBuildingsAtPoint`](https://github.com/tomalrussell/colouring-london/blob/master/app/src/api/building.ts#L20) doesn't currently include the edit history - may be worth adding edit history to that response too (other options possible based on time/round-trips/data volume trade-off).

**Comment by mz8i** [comment]
I think we need a mechanism for displaying correct category and data field labels when the data is displayed outside of the main view/edit window. For example in the multi-edit sidebar, currently the data is annotated by the database column name like `date_year`, rather than its UI label (`Year built (best estimate)`). For both multi-edit and edit history, it would be good to have proper titles for the fields.
I will submit an implementation proposal, but would be great to agree whether we want to work on this now or would rather have edit history sooner but with the database column labels (I don't think the full feature will be a lot more work than the simpler one) @tomalrussell @dominijk
